### PR TITLE
cmp - organize for editable install

### PR DESCRIPTION
**Pull request by claudioperez**
This is a great project! I am currently working with PEER at UC Berkeley to develop a new optimized Python interface for OpenSees that eliminates some of the existing vulnerabilities to global state corruption. I've started working on integrating this new interface into your package, but first, I needed to move the files into a subdirectory of `src` in order to run a local editable install with pip. Do you have a different installation method that would work for editable installs? If not, this pull request may ease future collaborations. 
The changes are:

- move everything under `src/` to a subdirectory named `src/planesections/`
- add a minimal `pyproject.toml` file to allow editable install (`pip install -e .`)

### CODE REVIEW

**Comment by cslotboom** [comment]
Hey, thanks for your PR! I'm really interested to see what changes are coming down the pipeline with the OpenSees interface!
I tried to make a system that allowed users to get type-hints and docstrings for opensees functions, but gave up on it..

To answer your question, I haven't used editable installs before, but I don't see any issue with implementing these changes.
I do want to do a bit of research before pulling anything into the main package - once I do that I'll follow up with any other changes I think should happen.

**Comment by claudioperez** [comment]
Thanks for considering the change! Take your time looking into it, and let me know if you have any better ideas! I'm just looking for a way to install locally. 
In case it helps, this is a nice resource for laying out Python packages: https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/

**Comment by cslotboom** [comment]
Hey, made a few changes to the pyproject.toml to match my old setup.py. After review, this works more easily than what I've been doing - in the next few days I'm going to confirm I can successfully upload to pypi under the new scheme then merge this in. Thanks for the suggestion!

**Comment by cslotboom** [comment]
Hey @claudioperez, I've confirmed I can still upload to PYPI with this setup, and am satisfied nothing is broken. This should be ready to merge, can you confirm everything is good on your end before I make the jump?

**Comment by claudioperez** [comment]
Yeah, everything looks great!

**Review by cslotboom — APPROVED** [review]

**Pull request merged**
